'use strict';

export const GAME_CREATION_REQUEST = 'GAME_CREATION_REQUEST';
export const GAME_CREATION_FAILURE = 'GAME_CREATION_FAILURE';
export const GAME_CREATION_SUCCESS = 'GAME_CREATION_SUCCESS';

export const GUESS_REQUEST = 'GUESS_REQUEST';
export const GUESS_FAILURE = 'GUESS_FAILURE';
export const GUESS_SUCCESS = 'GUESS_SUCCESS';
